version: 2.1,
jobs:
  build:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/nextjs-avadronity-website
    steps:
      - checkout
      - attach_workspace:
          at: ~/nextjs-avadronity-website
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            - dependencies-
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - ~/nextjs-avadronity-website/node_modules
          key: dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths: node_modules

  test:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/nextjs-avadronity-website
    steps:
      - checkout
      - attach_workspace:
          at: ~/nextjs-avadronity-website
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Format
          command: npm run format:check
      - run:
          name: Test
          command: npm run test
      - run:
          name: Coverage
          command: npm run coverage

  deploy:
    docker:
      - image: cimg/node:16.14.2
    working_directory: ~/nextjs-avadronity-website
    steps:
      - checkout
      - attach_workspace:
          at: ~/nextjs-avadronity-website
      - run:
          name: Deploy
          command: npm run deploy

workflows:
  version: 2.1
  build_app:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
