import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>AvaDronity</title>
        <meta name="description" content="Generated by Tolgahan Tolu" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <h1>Let's get started!</h1>
    </>
  );
}
