import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>AvaDronity</title>
        <meta name="description" content="Generated by Tolgahan Tolu" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" href="/logo.png" />
      </Head>
    </>
  );
}
