import Head from 'next/head';
import Navbar from '../components/Navbar/Navbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>AvaDronity</title>
        <meta name="description" content="Generated by Tolgahan Tolu" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar />
    </>
  );
}
